### ISSUE TITLE
vt: Argument list too long

### ISSUE THREAD

**Issue by SC-Duan** [DecodeGenetics/graphtyper-pipelines#5]
Hi,
I found an error when using this pipeline, the error message:
......
[D] Completed slice 1:322295001-322300000
Total wall-clock time of genotyping with Graphtyper (seconds):
22183
Total time (seconds):
22583
./graphtyper-pipelines/node_script.sh: line 140: /program/graphtyper/vt-0.57/vt: Argument list too long
[bcf_ordered_reader.cpp:49 BCFOrderedReader] Not a VCF/BCF file: -

The config:
REGION_START=1
REGION_SIZE=322297834 # 1 mb

When I change the "REGION_START=1, REGION_SIZE=1000000", it works well, but the result just includes SNPs located on 0-1000000bp, not whole chromosome 1.

When I using the "REGION_START=   , REGION_SIZE=1000000", it does not  work.

**Comment by hannespetur** [comment]
Hey,

the argument is too long for vt, but luckily they provide the option of inputting a file with all the filenames. I have pushed the necessary changes to the master branch.

However, I would like to note that I do not recommend running the whole chromosome 1 in a single region. The main benefit of the pipeline is the ability to run multiple regions in parallel. And even if you want to run them in serial you should use smaller regions because an error at the end of the chromosome would mean you need to rerun the entire chromosome again!

But if you really want to do this... it should work now.

All the best,
Hannes
